model:
  fusion: txt2img
  K: 1
  prompt_template: "a photo of x x"
  clip_model: "ViT-L/14"
  res_w: 0.8
  SA_K: 1
  width_img: 1024
  width_txt: 768

train:
  dataset: mit-states
  dataset_path: "../OADis/OADis/path/to/mitstates"
  lr: 0.0001
  attr_dropout: 0.3
  weight_decay: 0.00001
  context_length: 8
  train_batch_size: 128
  gradient_accumulation_steps: 2
  seed: 0
  epochs: 20
  epoch_start: 0
  save_path: data/model/mit-states
  load_model: False
  best_model_metric: best_unseen     #best_unseen  best_seen AUC best_loss best_hm
  sp_w: 0.1
  att: 0.01
  obj: 0.01
  attr_ours: 0
  phase: Fasle

test:
  eval_batch_size: 128
  open_world: True
  topk: 1
  text_encoder_batch_size: 36
  threshold: 0.4
  threshold_trials: 50
  bias: 0.001
  load_model:  data/model/mit-states/dfsp/txt2img_best.pt    # False or model path
  MCDP: False
  train_look_up_table: "val_nouse_fs"